# Automatically generated by: ros2nix --distro noetic
{ lib, buildRosPackage, asio, catkin, gtest, nlohmann_json, nodelet, openssl, resource-retriever, ros-babel-fish, ros-environment, roscpp, rosgraph-msgs, roslib, rostest, rosunit, std-msgs, std-srvs, websocketpp, zlib, fetchFromGitHub }:
buildRosPackage {
  pname = "ros-noetic-foxglove-bridge";

  version = "30-06-2025";

  # src = ./.;
  src = fetchFromGitHub {
    owner = "foxglove";
    repo = "ros-foxglove-bridge";
    rev = "f5c213f1cc59c5c336e9b899fbc07f7a8072c2b8";
    sha256 = "sha256-G8+rFO5mubGfvScF/czjjnwk0Fu0eD/qnL5EsVxUBYU=";
  };

  buildType = "catkin";
  buildInputs = [ asio catkin nlohmann_json ros-environment websocketpp ];
  checkInputs = [ gtest rostest rosunit std-msgs std-srvs ];
  propagatedBuildInputs = [ nodelet openssl resource-retriever ros-babel-fish roscpp rosgraph-msgs roslib zlib ];
  nativeBuildInputs = [ catkin ];

  meta = {
    description = "ROS Foxglove Bridge";
    license = with lib.licenses; [ mit ];
  };
}
